name: s3gui
description: S3 GUI for desktop and mobile.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  minio: ^3.5.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  timeago: ^3.3.0
  shared_preferences: ^2.0.15
  file_picker: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Balsamiq
      fonts:
        - asset: assets/fonts/Balsamiq-Sans.ttf
